default:
  app_name: fioRa
  app_version: !expr as.character(utils::packageVersion("fioRa"))
  app_date: !expr as.character(utils::packageDate("fioRa"))
  app_prod: no
  bam_server: yes
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
  app_version: development
  app_date: !expr as.character(Sys.Date())
